### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by rambletype** [eventespresso/espresso-certificates#1]
I'm getting the following error installing espresso-certificates on espresso 4.8.4p:
Warning: require_once(EVENT_ESPRESSO_PLUGINFULLPATHincludes/functions/database_install.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/espresso-certificates-master/espresso-certificates.php on line 76 Fatal error: require_once(): Failed opening required 'EVENT_ESPRESSO_PLUGINFULLPATHincludes/functions/database_install.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/wp-content/plugins/espresso-certificates-master/espresso-certificates.php on line 76

**Comment by nerrad** [comment]
espresso-certificates is an add-on for EE3 and is not compatible with EE4+
